version: '3.7'

services:
    nginx:
        container_name: nginx-rtmp
        image: alfg/nginx-rtmp:latest
        ports:
            - '1935:1935'
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./hls:/opt/data/hls
        networks:
            - app-network

    backend:
        container_name: backend-stream
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - DATABASE_URL=${DATABASE_URL}
        environment:
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - '8099:5000'
        depends_on:
            - db
        restart: always
        networks:
            - app-network

    client:
        container_name: client-stream
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 8080:3000
        depends_on:
            - backend
        restart: always
        networks:
            - app-network

    db:
        container_name: db-stream
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5432:5432'
        expose:
            - 5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
